### ISSUE TITLE
How to get the latest version of 'qa_generated.json' from Wikidata?

### ISSUE THREAD

**Issue by XZhang00** [sislab-unitn/DyKnow#1]
Hi, thanks for your solid work! 
Could you share the code or detailed instructions on how to build the latest version of 'qa_generated.json‘ from Wikidata?

Looking forward to your reply.

**Comment by mahedmousavi** [comment]
Hi, we are happy you find it interesting. We will share the code to generate the 'qa_generated.json‘ soon. A brief description as the procedure is available in the new version of our paper [https://arxiv.org/pdf/2404.08700]. Basically, 
1) we select the subject (entity name) and the relation (property), for instance "subject:Cristiano Ronaldo", and "property:sports team"
2) using Wikidata API we collect the data related to the selected subject by its unique wikidata ID  (subject:Cristiano Ronaldo, ID: Q11571) and (property:sports team, ID: P54). 
3) for each attribute value, we also collect the start and end times (properties P580 and P582).

as mentioned, we will release the code soon!!

does this explanation help you?

**Comment by XZhang00** [comment]
Thanks for your detailed reply! I will try it myself.
